title: "MAI-YUN HU"
description:  >-
  Data Science Portfolio - Projects, Resume and skills

show_download: true

theme: jekyll-theme-merlot

logo: /assets/img/profile.jpg
favicon: /assets/img/favicon.png
